server:
  port: ${SERVER_PORT}

spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:.env[.properties]
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN}
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 175000
  jpa:
    hibernate:
      ddl-auto: validate

domain:
  permission:
    admin:
      access-key: ${ADMIN_ACCESS_KEY}
      contact-secret-key: ${CONTACT_SECRET_KEY}
  policy:
    whitelist: ${WHITELIST}
    contact-limit: ${CONTACT_LIMIT}
    contact-limit-warning: ${CONTACT_LIMIT_WARNING}
    contact-price: ${TICKET_COST}
    ticket-price-policy: ${TICKET_PRICE_POLICY}
    ticket-price-registered-policy: ${TICKET_PRICE_REGISTERED_POLICY}

infra:
  openai:
    url: ${OPENAI_URL}
    api-key: ${OPENAI_API_KEY}
    model: ${OPENAI_MODEL}
    prompt: ${OPENAI_PROMPT}
    user-input: ${USER_INPUT_LIMIT}
  kakaopay:
    admin-key: ${KAKAOPAY_ADMIN_KEY}
    cid: ${KAKAOPAY_CID}
    approval-url: ${KAKAOPAY_APPROVAL_URL}
    cancel-url: ${KAKAOPAY_CANCEL_URL}
    fail-url: ${KAKAOPAY_FAIL_URL}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
