server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

domain:
  permission:
    admin:
      access-key: "DonaEmilyEatSteakLeopold"
      contact-secret-key : "ThisIsASecretKeyForContact"
  policy:
    whitelist: false
    contact-limit: 4
    contact-limit-warning: 2
    contact-price: 1
    ticket-price-policy: 2n20.4n40.6n60.8n80.10n100
    ticket-price-registered-policy: 1n10.3n30.5n50.7n70.9n90

infra:
  openai:
    url: "https://api.openai.com/v1/responses"
    api-key: "api-key-value"
    model: "gpt-4o-mini"
    prompt: "prompt for a developer"
    user-input: 100
  kakaopay:
    admin-key: "YOUR_KAKAO_ADMIN_KEY"
    cid: "TC0ONETIME"
    approval-url: "http://localhost:3000/payment/approve"
    cancel-url: "http://localhost:3000/payment/cancel"
    fail-url: "http://localhost:3000/payment/fail"
